spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1356
    url: jdbc:mysql://localhost:3307/air_tickets_booking_system?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    #Spring Boot默认是不注入这些属性值的,需要自己绑定
    druid:
      #druid数据源专有配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedstatements: true
      #配置监控统计拦截的filters,stat监控统计、Logback:日志记录、wall:防御sql注入
      filters: stat, slf4j
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=500
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
      filter:
        commons-log:
          statement-log-enabled: true
          statement-executable-sql-log-enable: true
        wall:
          config:
            multi-statement-allow: true
  jackson:
    time-zone: GMT+8

# mybatis
mybatis:
  typeAliasesPackage: cn.cuit.mapperocations
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:cn/cuit/mapper/*.xml
#logging
logging:
  config: classpath:logback-config.xml
  level:
    root: info
server:
  port: 8081

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


---
spring:
  profiles: prod

---
spring:
  profiles: test
